---
Name: placeholder-data-extension
After: '#elemental'
---
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - StevenPaw\SilverstripeStyleguide\Extensions\PlaceholderDataExtension

SilverStripe\Control\Director:
  rules:
    "datasheet//$Action/$ID": 'App\Controllers\DatasheetController'
    "placeholderpreview//$Action/$ID/$Name": 'StevenPaw\SilverstripeStyleguide\Controllers\PlaceholderPreviewController'
